services:
  postgres:
    image: postgres
    container_name: db-fullstack
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-fullstack
    environment:
      PGADMIN_DEFAULT_EMAIL: oscar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"